### ISSUE TITLE
Feature request: PTR Record

### ISSUE THREAD

**Issue by pptx704** [rockcavera/nim-ndns#4]
It would be really cool if we could provide an IP address and get the associated domain name with it (known as PTR record)? Is it possible to add such feature?

**Comment by rockcavera** [comment]
It is now available. See: [resolveRDns()](https://rockcavera.github.io/nim-ndns/ndns.html#resolveRDns%2CDnsClient%2Cstring%2Cint) and [asyncResolvRDns()](https://rockcavera.github.io/nim-ndns/ndns.html#asyncResolveRDns%2CDnsClient%2Cstring%2Cint).

**Comment by pptx704** [comment]
Oh right. Should've read the docs instead of examples only

**Comment by pptx704** [comment]
@rockcavera referring to this [SO Post](https://serverfault.com/questions/65781/multiple-reverse-dns-entries), wouldn't it make sense if RDNS query returns only one string instead of a sequence (maybe the first one if there are multiple)

**Comment by rockcavera** [comment]
And if there are multiple responses, how will they be retrieved? Better to return a sequence, with all the answers, and whoever just wants the first one, get `rdns[0]`. Is not true?

**Comment by pptx704** [comment]
I agree. Maybe add a wrapper function that returns just one PTR record (as that's what most people would likely need)?

**Comment by rockcavera** [comment]
Honestly, I don't see any reason for this, given that the current proc fully covers the PTR query.
